# Generated by Django 4.2.16 on 2025-11-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('body_id', models.IntegerField(db_column='BodyID', primary_key=True, serialize=False)),
                ('body_name', models.CharField(db_column='BodyName', max_length=255)),
            ],
            options={
                'db_table': 'Bodies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('drive_type_id', models.IntegerField(db_column='DriveTypeID', primary_key=True, serialize=False)),
                ('drive_type_name', models.CharField(db_column='DriveTypeName', max_length=255)),
            ],
            options={
                'db_table': 'DriveTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('make_id', models.IntegerField(db_column='MakeID', primary_key=True, serialize=False)),
                ('make_name', models.CharField(db_column='Make', max_length=255)),
            ],
            options={
                'db_table': 'Makes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MakeModel',
            fields=[
                ('model_id', models.IntegerField(db_column='ModelID', primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_column='ModelName', max_length=255)),
            ],
            options={
                'db_table': 'MakeModels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('sub_model_id', models.IntegerField(blank=True, db_column='SubModelID', null=True)),
                ('vehicle_display_name', models.CharField(blank=True, db_column='Vehicle_Display_Name', max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('engine', models.CharField(blank=True, db_column='Engine', max_length=255, null=True)),
                ('engine_cc', models.IntegerField(blank=True, db_column='Engine_CC', null=True)),
                ('engine_cylinders', models.IntegerField(blank=True, db_column='Engine_Cylinders', null=True)),
                ('engine_liter_display', models.FloatField(blank=True, db_column='Engine_Liter_Display', null=True)),
                ('fuel_type_id', models.IntegerField(blank=True, db_column='FuelTypeID', null=True)),
                ('num_doors', models.IntegerField(blank=True, db_column='NumDoors', null=True)),
            ],
            options={
                'db_table': 'VehicleDetails',
                'managed': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='SearchAnalytics',
        ),
        migrations.RemoveField(
            model_name='vehicleimage',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='VehicleImage',
        ),
    ]
