# Generated by Django 4.2.16 on 2025-11-26 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_review_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('custom_title', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='api.vehicledetail')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.vehicledetail')),
            ],
        ),
    ]
