# Generated by Django 4.2.16 on 2025-11-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_homepagefeature_searchanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagefeature',
            name='description_ar',
            field=models.TextField(default='Arabic Description'),
        ),
        migrations.AddField(
            model_name='homepagefeature',
            name='title_ar',
            field=models.CharField(default='Arabic Title', max_length=100),
        ),
    ]
