# Generated by Django 4.2.16 on 2025-12-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_homepagefeature_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemetadata',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
